services:
  # Main API Service
  - type: web
    name: birjob-ios-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: birjob-postgres
          property: connectionString
      - key: UPSTASH_REDIS_REST_URL
        value: "https://strong-kiwi-38087.upstash.io"
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "AZTHAAIjcDE0MjVmZDQwMmY2MGY0ZDlmYjgwY2EwYzNmZDI5OWFmM3AxMA"
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: APNS_SANDBOX
        value: "true"
      - key: APNS_KEY_PATH
        value: "/etc/secrets/apn.p8"
      - key: APNS_KEY_ID
        value: "DKK5M29XQJ"
      - key: APNS_TEAM_ID
        value: "G9KT8SLBVR"  
      - key: APNS_BUNDLE_ID
        value: "az.birjob.jobapp"
    healthCheckPath: /api/v1/health
    autoDeploy: false
    


databases:
  # PostgreSQL Database
  - name: birjob-postgres
    plan: starter